# Generated by Django 6.0.7 on 2026-08-03 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0002_alter_logfile_options_logfile_original_filename_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('error_type', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=20)),
                ('root_cause', models.TextField()),
                ('recommendation', models.TextField()),
                ('ai_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='logs.logfile')),
            ],
        ),
    ]
