# Generated by Django 6.0.7 on 2026-08-09 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('resolved', 'Resolved'), ('info', 'Info')], default='info', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('recommended_solution', models.TextField(blank=True)),
                ('code_fix', models.TextField(blank=True)),
                ('runtime_framework', models.CharField(blank=True, max_length=255)),
                ('cluster_node', models.CharField(blank=True, max_length=255)),
                ('thread_context', models.CharField(blank=True, max_length=255)),
                ('confidence_score', models.FloatField(default=0)),
                ('analysis_latency', models.FloatField(default=0)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='logs.logfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
