# Generated by Django 6.0.7 on 2026-08-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Log File', 'verbose_name_plural': 'Log Files'},
        ),
        migrations.AddField(
            model_name='logfile',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='file_size',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='file_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='UPLOADED', max_length=20),
        ),
    ]
