import { useState } from "react";
import { Brain, Code, AlertTriangle, ShieldAlert, CheckCircle2 } from "lucide-react";
import DashboardSidebar from "../components/DashboardSidebar";
import DashboardHeader from "../components/DashboardHeader";
import "../styles/dashboard.css";

function AnalysisResult() {
  const [collapsed, setCollapsed] = useState(false);

  return (
    <div className={`db-layout${collapsed ? " sidebar-collapsed" : ""}`}>
      <DashboardSidebar
        collapsed={collapsed}
        onToggle={() => setCollapsed((c) => !c)}
      />

      <div className="db-main">
        <DashboardHeader />

        <div className="db-content">
          <div className="db-page-heading">
            <h1 className="db-page-title">AI Analysis Result</h1>
            <p className="db-page-subtitle">
              Detailed threat and exception diagnostics generated by the GeerGoo AI engine.
            </p>
          </div>

          <div style={{ display: "grid", gridTemplateColumns: "1fr 2fr", gap: "24px", alignItems: "start" }}>
            
            {/* Left Column: Diagnostics Metadata */}
            <div className="db-card" style={{ display: "flex", flexDirection: "column", gap: "20px" }}>
              <div style={{ borderBottom: "1px solid var(--c-border)", paddingBottom: "12px" }}>
                <h3 style={{ fontSize: "0.875rem", fontWeight: 600, color: "var(--c-text-1)" }}>Diagnostics Metadata</h3>
              </div>

              <div>
                <p style={{ fontSize: "0.6875rem", textTransform: "uppercase", letterSpacing: "0.08em", color: "var(--c-text-3)", fontWeight: 500, display: "flex", alignItems: "center", gap: "6px" }}>
                  <Code size={12} /> Language
                </p>
                <p style={{ fontSize: "0.875rem", color: "var(--c-text-1)", marginTop: "4px", fontWeight: 500 }}>Python</p>
              </div>

              <div>
                <p style={{ fontSize: "0.6875rem", textTransform: "uppercase", letterSpacing: "0.08em", color: "var(--c-text-3)", fontWeight: 500, display: "flex", alignItems: "center", gap: "6px" }}>
                  <AlertTriangle size={12} /> Error Type
                </p>
                <p style={{ fontSize: "0.875rem", color: "var(--c-text-1)", marginTop: "4px", fontWeight: 500 }}>IndexError</p>
              </div>

              <div>
                <p style={{ fontSize: "0.6875rem", textTransform: "uppercase", letterSpacing: "0.08em", color: "var(--c-text-3)", fontWeight: 500, display: "flex", alignItems: "center", gap: "6px" }}>
                  <ShieldAlert size={12} /> Severity
                </p>
                <span className="db-status critical" style={{ marginTop: "6px" }}>
                  <span className="db-status-dot" />
                  High Severity
                </span>
              </div>
            </div>

            {/* Right Column: AI Analysis Cards */}
            <div style={{ display: "flex", flexDirection: "column", gap: "16px" }}>
              
              {/* Summary Card */}
              <div className="db-card">
                <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "12px" }}>
                  <div style={{ color: "var(--c-accent)" }}>
                    <Brain size={18} />
                  </div>
                  <h3 style={{ fontSize: "0.875rem", fontWeight: 650, color: "var(--c-text-1)" }}>AI Summary</h3>
                </div>
                <p style={{ fontSize: "0.9375rem", color: "var(--c-text-2)", lineHeight: "1.6" }}>
                  The application attempted to access an element of a list at an index value that is out of its bounds. This typically results in immediate program termination if unhandled.
                </p>
              </div>

              {/* Recommended Fix Card */}
              <div className="db-card">
                <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "12px" }}>
                  <div style={{ color: "var(--c-success)" }}>
                    <CheckCircle2 size={18} />
                  </div>
                  <h3 style={{ fontSize: "0.875rem", fontWeight: 650, color: "var(--c-text-1)" }}>Recommended Fix</h3>
                </div>
                <p style={{ fontSize: "0.9375rem", color: "var(--c-text-2)", lineHeight: "1.6" }}>
                  Implement pre-validation bounds checking on the list array before accessing specific index positions. Ensure list length is strictly greater than the index value you are querying.
                </p>
              </div>

            </div>

          </div>
        </div>
      </div>
    </div>
  );
}

export default AnalysisResult;